// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcplrhmzywhmhexkxoee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjcGxyaG16eXdobWhleGt4b2VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMzU2OTksImV4cCI6MjA1NTcxMTY5OX0.8TPYH7dvVEh2_cTkZTFqRPR-Cf22VTpUEbEEvwhMLkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);